version: '3'
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24

services:
  toposoid-deduction-admin-web:
    image: toposoid/toposoid-deduction-admin-web:0.4-SNAPSHOT
    tty: true
    environment:
      - GRAPHDB_HOST=172.30.0.2
      - PRIVATE_IP_ADDRESS=localhost
      - PLAY_HTTP_PORT=9003
      - TOPOSOID_DEDUCTION_UNIT1_HOST=172.30.0.10
      - TOPOSOID_DEDUCTION_UNIT2_HOST=172.30.0.11
      - TOPOSOID_DEDUCTION_UNIT2_HOST=172.30.0.12
      - SCALA_DATA_ACCESSOR_NEO4J_WEB_HOST=172.30.0.3
    networks:
      app_net:
        ipv4_address: 172.30.0.6
    ports:
      - 9003:9003
    depends_on:
      - toposoid-deduction-unit-exact-match-web
  toposoid-deduction-unit-exact-match-web:
    image: toposoid/toposoid-deduction-unit-exact-match-web:0.4-SNAPSHOT
    tty: true
    environment:
      - GRAPHDB_HOST=172.30.0.2
      - PRIVATE_IP_ADDRESS=172.30.0.10
      - SCALA_DATA_ACCESSOR_NEO4J_WEB_HOST=172.30.0.3
      - PLAY_HTTP_PORT=9101
    networks:
      app_net:
        ipv4_address: 172.30.0.10
    ports:
      - 9101:9101
    depends_on:
      - scala-data-accessor-neo4j-web
  toposoid-deduction-unit-synonym-match-web:
    image: toposoid/toposoid-deduction-unit-synonym-match-web:0.4-SNAPSHOT
    environment:
      - PRIVATE_IP_ADDRESS=172.30.0.11
      - SCALA_DATA_ACCESSOR_NEO4J_WEB_HOST=172.30.0.3
      - PLAY_HTTP_PORT=9102
    networks:
      app_net:
        ipv4_address: 172.30.0.11
    ports:
      - 9102:9102
    depends_on:
      - scala-data-accessor-neo4j-web
  toposoid-deduction-unit-sentence-vector-match-web:
    image: toposoid/toposoid-deduction-unit-sentence-vector-match-web:0.4-SNAPSHOT
    environment:
      - PRIVATE_IP_ADDRESS=172.30.0.12
      - SCALA_DATA_ACCESSOR_NEO4J_WEB_HOST=172.30.0.3
      - TOPOSOID_VALD_ACCESSOR_HOST=172.30.0.13
      - TOPOSOID_VALD_SEARCH_NUM_MAX=5
      - PLAY_HTTP_PORT=9103
    networks:
      app_net:
        ipv4_address: 172.30.0.12
    ports:
      - 9103:9103
    depends_on:
      - scala-data-accessor-neo4j-web
      - data-accessor-vald-web
  scala-data-accessor-neo4j-web:
    image: toposoid/scala-data-accessor-neo4j-web:0.4-SNAPSHOT
    environment:
      - GRAPHDB_HOST=172.30.0.2
      - PRIVATE_IP_ADDRESS=172.30.0.3
      - PLAY_HTTP_PORT=9005
    networks:
      app_net:
        ipv4_address: 172.30.0.3
    ports:
      - 9005:9005
    depends_on:
      - neo4j
  neo4j:
    image: neo4j:4.1.3
    environment:
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_AUTH=neo4j/p@ssw0rd
    ports:
      - 7474:7474
      - 7687:7687
    networks:
      app_net:
        ipv4_address: 172.30.0.2
  data-accessor-vald-web:
    image: toposoid/data-accessor-vald-web:0.4-SNAPSHOT
    environment:
      - TOPOSOID_VALD_HOST=172.30.0.14
      - TOPOSOID_VALD_PORT=8081
      - TOPOSOID_VALD_DISTANCE_THRESHHOLD=0.25 #For Multilingual Model 0.03
    networks:
      app_net:
        ipv4_address: 172.30.0.13
    ports:
      - 9010:9010
  vald:
    image: vdaas/vald-agent-ngt:v1.6.3
    user: 1000:1000
    volumes:
      - ./vald-config:/etc/server
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    networks:
      app_net:
        ipv4_address: 172.30.0.14
    ports:
      - 8081:8081


